language: ruby

cache:
  - bundler

install:
  - bundle install

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4

script:
  - bundle exec rake default
  - gem build sensu-plugins-dovecot.gemspec
  - gem install sensu-plugins-dovecot-*.gem

deploy:
  provider: rubygems
  api_key: xxx
  gem: sensu-plugins-dovecot
  on:
    tags: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3
    rvm: 2.4
    repo: ushis/sensu-plugins-dovecot
